const PRODUCTS_DATA = [
  {
    "id": "provence",
    "name": "Provence",
    "price": 1200,
    "category": "aromatike",
    "tag": "Aromatike · Lavandë",
    "image": "images/il_1588xN.7666017445_c4ol.avif",
    "badge": "Bestseller",
    "hours": "45 orë",
    "wax": "Dyllë soje",
    "size": "200g",
    "scent": "Lavandë · Nenexhik · Musk i bardhë",
    "ingredients": "Dyllë soje organik, aroma eterike lavandë, fitil pambuku",
    "description": "Provence ju transporton në fushat e lavandës franceze me aromën e tij të pastër dhe qetësuese. I krijuar nga dyllë soje organik, ky qiri ofron një djegie të pastër dhe të gjatë pa asnjë kimikalie artificiale."
  },
  {
    "id": "verde-pillar",
    "name": "Verde Pillar",
    "price": 1550,
    "category": "dekorative",
    "tag": "Dekorative · Ambient",
    "image": "images/soy candles.webp",
    "badge": null,
    "hours": "60 orë",
    "wax": "Dyllë soje",
    "size": "300g",
    "scent": "Erë druri · Sandalwood · Cedër",
    "ingredients": "Dyllë soje, aroma bimore, fitil pambuku organik",
    "description": "Verde Pillar është qiri dekorativ i krijuar për të sjellë elegancë në çdo ambient. Forma e tij e lartë dhe e drejtë e bën perfekt për tryeza dhe dekorime shtëpiake moderne."
  },
  {
    "id": "lumiere-classic",
    "name": "Lumière Classic",
    "price": 850,
    "category": "ekologjike",
    "tag": "Ekologjike · Vanilje",
    "image": "images/il_1588xN.3162499558_i4yy.webp",
    "badge": "I ri",
    "hours": "55 orë",
    "wax": "Dyllë natyral",
    "size": "180g",
    "scent": "Vanilje · Sandalwood · Amber",
    "ingredients": "Dyllë natyral bimor, aroma vanilje & sandalwood, fitil pambuku",
    "description": "Lumière Classic është firma jonë — kombinimi perfekt i vaniljes së ngrohtë dhe sandalwood-it ekzotik. Ky qiri ekologjik prodhohet me dyllë 100% natyral dhe ambalazh të riciklueshëm."
  },
  {
    "id": "set-krishtlindjesh",
    "name": "Set Krishtlindjesh",
    "price": 2800,
    "category": "festive",
    "tag": "Festive · Set",
    "image": "images/il_1588xN.7394624854_oa4i.webp",
    "badge": null,
    "hours": "50 orë (secili)",
    "wax": "Dyllë natyral",
    "size": "Set 2 copë · 150g secili",
    "scent": "Pishe · Kanellë · Portokall · Karafil",
    "ingredients": "Dyllë natyral, aroma pishe & kanellë, fitil pambuku, kuti dhuratë",
    "description": "Set Krishtlindjesh është dhurata perfekte festive. Përfshin 2 qirinj artizanalë me aromë pishe dhe kanellë, të paketuar në kuti dhuratë elegante me dekor dimëror."
  },
  {
    "id": "rosa-serata",
    "name": "Rosa Serata",
    "price": 1100,
    "category": "romantike",
    "tag": "Romantike · Trëndafil",
    "image": "images/rosaserata.jpg",
    "badge": null,
    "hours": "40 orë",
    "wax": "Dyllë soje",
    "size": "160g",
    "scent": "Trëndafil · Musk · Lychee",
    "ingredients": "Dyllë soje organik, aroma trëndafil & musk, fitil pambuku",
    "description": "Rosa Serata është qiri i dashurisë — aroma e trëndafilit të freskët e kombinuar me musk të butë krijon atmosferën perfekte për mbrëmje romantike dhe momente të veçanta."
  },
  {
    "id": "amber-nuit",
    "name": "Amber Nuit",
    "price": 1350,
    "category": "aromatike",
    "tag": "Premium · Amber & Oud",
    "image": "images/20260110-AmberNoirCandle.webp",
    "badge": null,
    "hours": "50 orë",
    "wax": "Dyllë natyral",
    "size": "220g",
    "scent": "Amber · Oud · Sandal · Pakuli",
    "ingredients": "Dyllë natyral premium, aroma amber & oud, fitil pambuku organik",
    "description": "Amber Nuit është koleksioni ynë premium — një udhëtim shqisor nëpër Lindjen e Mesme me aromën e pasur të amberit dhe oud-it. Për ata që duan diçka ekstraordinare."
  },
  {
    "id": "citrus-garden",
    "name": "Citrus Garden",
    "price": 980,
    "category": "aromatike",
    "tag": "Aromatike · Agrume",
    "image": "images/citrus candle.png",
    "badge": null,
    "hours": "38 orë",
    "wax": "Dyllë soje",
    "size": "150g",
    "scent": "Portokall · Limon · Grejpfrut · Baziliku",
    "ingredients": "Dyllë soje, aroma agrume, fitil pambuku natyral",
    "description": "Citrus Garden sjell freskinë e një kopshti mesdhetar brenda shtëpisë suaj. Kombinimi i agrumeve të ndritshme me barishtë të freskëta krijon atmosferë energjizuese."
  },
  {
    "id": "forest-pine",
    "name": "Forest Pine",
    "price": 1650,
    "category": "ekologjike",
    "tag": "Ekologjike · Pishe",
    "image": "images/il_600x600.7475990337_5j8y.avif",
    "badge": null,
    "hours": "65 orë",
    "wax": "Dyllë natyral",
    "size": "280g",
    "scent": "Pishe · Dëllinjë · Tokë e lagur · Cedër",
    "ingredients": "Dyllë natyral ekologjik, aroma pishe & dëllinjë, fitil pambuku organik",
    "description": "Forest Pine ju fut në zemër të një pylli të heshtur dimëror. Aroma e pishe dhe dëllinjës krijon ndjesi të pastërtisë natyrore dhe qetësisë absolute."
  },
  {
    "id": "mini-votive-set",
    "name": "Mini Votive Set",
    "price": 720,
    "oldPrice": 900,
    "category": "dekorative",
    "tag": "Dekorative · Set 3 copë",
    "image": "images/minivotive.webp",
    "badge": "–20%",
    "hours": "20 orë (secili)",
    "wax": "Dyllë soje",
    "size": "Set 3 copë · 60g secili",
    "scent": "Vanilje · Lavandë · Portokall",
    "ingredients": "Dyllë soje, aroma mikse natyrale, fitil pambuku",
    "description": "Mini Votive Set është zgjedhja perfekte për dekorim — tre qirinj të vegjël votiv të vendosur strategjikisht mund të transformojnë çdo hapësirë. Ideale si dhuratë ose për dekorim tryeze."
  },
  {
    "id": "velvet-rose",
    "name": "Velvet Rose",
    "price": 1800,
    "category": "romantike",
    "tag": "Romantike · Premium",
    "image": "images/velvet rose.jpg",
    "badge": null,
    "hours": "55 orë",
    "wax": "Dyllë natyral",
    "size": "240g",
    "scent": "Trëndafil i kuq · Velvet Musk · Patchouli",
    "ingredients": "Dyllë natyral premium, aroma trëndafil & velvet musk, fitil pambuku organik",
    "description": "Velvet Rose është qiri premium romantik — aroma e trëndafilit të kuq të kombinuar me velvet musk krijon një eksperiencë sensuale dhe të paharrueshme."
  },
  {
    "id": "set-ditelindjesh",
    "name": "Set Ditëlindjesh",
    "price": 3200,
    "category": "festive",
    "tag": "Festive · Dhuratë",
    "image": "images/gift box2.avif",
    "badge": null,
    "hours": "60 orë (total)",
    "wax": "Dyllë natyral",
    "size": "Set 3 copë · kuti premium",
    "scent": "Vanilje · Karamel · Lule limoni",
    "ingredients": "Dyllë natyral, aroma mikse festive, fitil pambuku, kuti luksioze",
    "description": "Set Ditëlindjesh është dhurata ideale — një koleksion qirinjsh premium të paketuar me kujdes në kutie luksioze. Çdo qiri ka aromën e vet unike."
  },
  {
    "id": "ivory-column",
    "name": "Ivory Column",
    "price": 1100,
    "category": "dekorative",
    "tag": "Dekorative · Kolonë",
    "image": "images/ivory candles.jpg",
    "badge": null,
    "hours": "48 orë",
    "wax": "Dyllë natyral",
    "size": "320g",
    "scent": "Pa aromë · Dekorativ",
    "ingredients": "Dyllë natyral i bardhë, fitil pambuku organik",
    "description": "Ivory Column është eleganca në formën e saj më të pastër — qiri kolonë i bardhë krejtazi, pa aromë, i krijuar ekskluzivisht për dekorim. Formë e lartë dhe precize."
  },
  {
    "id": "lavender-wonder",
    "name": "Lavender Wonder",
    "price": 1450,
    "category": "aromatike",
    "tag": "Aromatike · Lavandë",
    "image": "images/lavender.jpg",
    "badge": null,
    "hours": "50 orë",
    "wax": "Dyllë natyral",
    "size": "200g",
    "scent": "Lavandë intensive · Kamonille · Cedër",
    "ingredients": "Dyllë natyral, aroma lavandë eterike, fitil pambuku",
    "description": "Lavender Wonder është qiri terapeutik me aromë lavandë intensive — ideal për relaksim, meditim dhe gjumë të qetë. Aroma e tij e pastër ndihmon në uljen e stresit."
  },
  {
    "id": "lavender-mini-glow",
    "name": "Lavender Mini Glow",
    "price": 1190,
    "category": "aromatike",
    "tag": "Aromatike · Lavandë",
    "image": "images/lavender2.jpg",
    "badge": null,
    "hours": "45 orë",
    "wax": "Dyllë natyral",
    "size": "150g",
    "scent": "Lavandë · Musk i bardhë",
    "ingredients": "Dyllë natyral, aroma lavandë & musk, fitil pambuku",
    "description": "Lavender Mini Glow është versioni kompakt i qirinjve tanë të lavandës — perfekt për dhomë gjumi, banjë ose zyrë. I vogël por me aromë të fuqishme dhe të qëndrueshme."
  },
  {
    "id": "pure-crafted-lavender",
    "name": "Pure & Crafted Lavender",
    "price": 2500,
    "category": "ekologjike",
    "tag": "Ekologjike · Lavandë & Kamonille",
    "image": "images/lavender 3.avif",
    "badge": null,
    "hours": "70 orë",
    "wax": "Dyllë natyral",
    "size": "300g",
    "scent": "Lavandë alpine · Kamonille · Neroli",
    "ingredients": "Dyllë soje organik certifikuar, aroma eterike lavandë & kamonille, fitil pambuku bio",
    "description": "Pure & Crafted Lavender është qiri ekologjik premium — kombinim i lavandës alpine me kamonillen e butë. Koha më e gjatë e djegies dhe aroma më e pastër."
  },
  {
    "id": "rose-vanilla-dream",
    "name": "Rose and Vanilla DREAM",
    "price": 2980,
    "category": "aromatike",
    "tag": "Aromatike · Trëndafil & Vanilje",
    "image": "images/trendafil&vanilje.avif",
    "badge": null,
    "hours": "50 orë",
    "wax": "Dyllë natyral",
    "size": "220g",
    "scent": "Trëndafil · Vanilje · Muscat",
    "ingredients": "Dyllë natyral, aroma trëndafil & vanilje, fitil pambuku organik",
    "description": "Rose and Vanilla DREAM është kombinimi perfekt i dy aromave klasike. Një qiri që gjithmonë krijon atmosferën e duhur dhe nuk kalon kurrë nga moda."
  },
  {
    "id": "cookies-and-cream",
    "name": "Cookies and Cream",
    "price": 3450,
    "category": "festive",
    "tag": "Festive · Cookies & Cream",
    "image": "images/set fete.webp",
    "badge": null,
    "hours": "74 orë",
    "wax": "Dyllë natyral",
    "size": "350g",
    "scent": "Vanilje · Kakao · Krem · Biskotat",
    "ingredients": "Dyllë natyral, aroma biskotash & vanilje, fitil pambuku",
    "description": "Cookies and Cream sjell aromën e ëmbël të biskotave sapo dalë nga furra — krijon atmosferën e ngrohtë të festave familjare dhe momenteve të lumtura."
  },
  {
    "id": "glow-globes",
    "name": "Glow Globes",
    "price": 4000,
    "category": "festive",
    "tag": "Festive · Sandalwood",
    "image": "images/set krishlindje.jpg",
    "badge": null,
    "hours": "56 orë",
    "wax": "Dyllë natyral",
    "size": "280g",
    "scent": "Sandalwood · Musk i bardhë · Amber",
    "ingredients": "Dyllë natyral premium, aroma sandalwood & musk, fitil pambuku organik",
    "description": "Glow Globes është koleksioni ynë premium festiv — sfera qirinjsh me sandalwood dhe musk të bardhë. Formë e rrumbullakët unike dhe aromë sophisticated."
  },
  {
    "id": "flower-bloom",
    "name": "Flower Bloom",
    "price": 2200,
    "category": "dekorative",
    "tag": "Dekorative · Amber & Oud",
    "image": "images/dekorativ.webp",
    "badge": null,
    "hours": "48 orë",
    "wax": "Dyllë natyral",
    "size": "250g",
    "scent": "Amber · Oud · Lule të egra · Çaj jeshil",
    "ingredients": "Dyllë natyral, aroma amber & lule, fitil pambuku organik",
    "description": "Flower Bloom kombinon estetikën dekorative me aromën e pasur të amberit dhe oud-it. Formë florore unike e punuar me dorë, ideale si element dekorativ kryesor."
  },
  {
    "id": "love-spell",
    "name": "Love Spell",
    "price": 1790,
    "category": "romantike",
    "tag": "Romantike · Premium",
    "image": "images/lovespell.webp",
    "badge": null,
    "hours": "42 orë",
    "wax": "Dyllë natyral",
    "size": "190g",
    "scent": "Lule ekzotike · Musk · Vanilje · Sandalwood",
    "ingredients": "Dyllë natyral premium, aroma blend romantike, fitil pambuku",
    "description": "Love Spell është magjia e aromës romantike — një blend sekret i luleve ekzotike dhe muskut të butë që krijon tërheqjen e papërmbajtshme."
  },
  {
    "id": "prosperity-candle",
    "name": "Prosperity Candle",
    "price": 2700,
    "category": "ekologjike",
    "tag": "Ekologjike · Agrume",
    "image": "images/ekologjike.webp",
    "badge": null,
    "hours": "55 orë",
    "wax": "Dyllë soje",
    "size": "260g",
    "scent": "Grejpfrut · Limon · Barishtë · Menta",
    "ingredients": "Dyllë soje organik certifikuar, aroma agrume eterike, fitil pambuku bio",
    "description": "Prosperity Candle është qiri ekologjik me aromë agrumesh energjizuese — grejpfruti dhe limoni i kombinuar me barishtë të freskëta krijon atmosferën e suksesit."
  },
  {
    "id": "halloween-pumpkin",
    "name": "Halloween Pumpkin",
    "price": 3000,
    "category": "festive",
    "tag": "Festive · Portokall Premium",
    "image": "images/halloween.webp",
    "badge": "Limited",
    "hours": "60 orë",
    "wax": "Dyllë soje",
    "size": "300g",
    "scent": "Kungull · Kanellë · Karafil · Nutmeg",
    "ingredients": "Dyllë soje, aroma kungull & kanellë, fitil pambuku natyral",
    "description": "Halloween Pumpkin sjell aromën ikonike të festës — kungull, kanellë dhe karafil të kombinuara për atmosferën e përsosur. Edicion i kufizuar sezonale."
  },
  {
    "id": "customized-box-holder",
    "name": "Customized Box Holder",
    "price": 900,
    "category": "aksesore",
    "tag": "Aksesorë · Mbajtëse",
    "image": "images/aksesor6.webp",
    "badge": null,
    "hours": "–",
    "wax": "–",
    "size": "15 x 15 cm",
    "scent": "Pa aromë",
    "ingredients": "Dru natyral, ngjyra eko",
    "description": "Customized Box Holder është mbajtëse dekorative e punuar me dorë nga druri natyral. Perfekte për qirinjtë votiv dhe pillar, mund të personalizohet me mesazhin tuaj."
  },
  {
    "id": "candle-stylish-holders",
    "name": "Candle Stylish Holders",
    "price": 1400,
    "category": "aksesore",
    "tag": "Aksesorë · Premium",
    "image": "images/AKSESORE1.webp",
    "badge": null,
    "hours": "–",
    "wax": "–",
    "size": "Set 2 copë",
    "scent": "Pa aromë",
    "ingredients": "Metal i punuar, qelq, dizajn modern",
    "description": "Candle Stylish Holders janë mbajtëse premium me dizajn modern — set 2 copë ideal për qirinj pillar dhe votiv. Dizajn minimalist që i shton vlerë çdo hapësire."
  },
  {
    "id": "harvest-warmth",
    "name": "Harvest Warmth",
    "price": 1500,
    "category": "festive",
    "tag": "Dimërore · Mollë & Kanellë",
    "image": "images/kolekdiondimri2.webp",
    "badge": "Dimër 2026",
    "hours": "52 orë",
    "wax": "Dyllë natyral",
    "size": "200g",
    "scent": "Mollë · Kanellë · Karafil · Nutmeg",
    "ingredients": "Dyllë natyral, aroma mollë & kanellë, fitil pambuku organik",
    "description": "Harvest Warmth sjell ngrohtësinë e stinës së vjeshtës dhe dimrit — mollë e pjekur, kanellë dhe karafil krijojnë aromën perfekte të shtëpisë."
  },
  {
    "id": "winter-spice",
    "name": "Winter Spice",
    "price": 1750,
    "category": "festive",
    "tag": "Dimërore · Erëza",
    "image": "images/koleksion_dimri.avif",
    "badge": "Dimër 2026",
    "hours": "58 orë",
    "wax": "Dyllë natyral",
    "size": "240g",
    "scent": "Kanellë · Vanilje · Yll anisi · Kardamom",
    "ingredients": "Dyllë natyral premium, aroma erëzash dimërore, fitil pambuku bio",
    "description": "Winter Spice është kokteli ynë aromatik i dimrit — erëza ekzotike, vanilje e ngrohtë dhe kardamom krijon atmosferën e festave dhe momenteve familjare."
  },
  {
    "id": "frozen-pine",
    "name": "Frozen Pine",
    "price": 1900,
    "category": "festive",
    "tag": "Dimërore · Pishe & Borë",
    "image": "images/koleksiondimri3.avif",
    "badge": "Dimër 2026",
    "hours": "60 orë",
    "wax": "Dyllë natyral",
    "size": "260g",
    "scent": "Pishe · Borë · Dëllinjë · Cedër",
    "ingredients": "Dyllë natyral ekologjik, aroma pishe & borë, fitil pambuku organik",
    "description": "Frozen Pine të transporton në një pyllin dimëror të mbuluar me borë — pishe alpine, dëllinjë dhe freski bore krijojnë qetësinë dhe pastërtinë absolute."
  },
  {
    "id": "birthday-candle-gift-box",
    "name": "Birthday Candle Gift Box",
    "price": 2500,
    "category": "festive",
    "tag": "Dhuratë · Ditëlindje",
    "image": "images/gift6.webp",
    "badge": "Bestseller",
    "hours": "45 orë",
    "wax": "Dyllë natyral",
    "size": "Set komplet",
    "scent": "Lavandë · Vanilje · Trëndafil",
    "ingredients": "Dyllë natyral, aroma mikse, fitil pambuku, pako rozë elegante",
    "description": "Set komplet me qiri aromatik, pako rozë elegante dhe kartë urimesh. Surprizë e plotë për ditëlindjen e dikujt të dashur."
  },
  {
    "id": "candle-wick-trimmer-set",
    "name": "Candle & Wick Trimmer Set",
    "price": 1800,
    "category": "aksesore",
    "tag": "Dhuratë · Set Premium",
    "image": "images/giftset.webp",
    "badge": "",
    "hours": "50 orë",
    "wax": "Dyllë natyral",
    "size": "Set 3 copë",
    "scent": "Sandalwood · Amber",
    "ingredients": "Dyllë natyral, aroma sandalwood, fitil pambuku + wick trimmer ari",
    "description": "Qiri artizanal + wick trimmer ari + shkrepëse dekorative. Seti i plotë për dashamirësit e qirinjve."
  },
  {
    "id": "wedding-favor-set",
    "name": "Wedding Favor Set",
    "price": 4500,
    "category": "festive",
    "tag": "Dhuratë · Dasma",
    "image": "images/setvotiv.webp",
    "badge": "Dasma",
    "hours": "20 orë (secili)",
    "wax": "Dyllë soje",
    "size": "Set 9 copë",
    "scent": "Trëndafil · Musk · Lule të egra",
    "ingredients": "Dyllë soje organik, aroma lulesh, fitil pambuku, mbajtëse druri, lule të thara",
    "description": "Set 9 qirinjsh votiv në mbajtëse druri me lule të thara — favoret ideale për dasma dhe evente."
  },
  {
    "id": "mini-tealight-set",
    "name": "Mini Tealight Set",
    "price": 1400,
    "category": "dekorative",
    "tag": "Dhuratë · Mini Set",
    "image": "images/set dasme.webp",
    "badge": "Natyral",
    "hours": "15 orë (secili)",
    "wax": "Dyllë soje",
    "size": "Set 6 copë",
    "scent": "Vanilje · Lavandë · Portokall",
    "ingredients": "Dyllë soje natyral, aroma mikse, fitil pambuku mini",
    "description": "Set qirinjsh mini natyralë — të bukur, aromatikë dhe perfektë si favor eventi ose dhuratë e vogël."
  },

  {
  "id": "seti-krishtlindjesh",
  "name": "Set Krishtlindjesh",
  "price": 2800,
  "category": "festive",
  "tag": "Festive · Set",
  "image": "images/krishtlidje.webp",
  "badge": "Dimër",
  "hours": "50 orë (secili)",
  "wax": "Dyllë soje natyral",
  "size": "Set 2 qirinj + kuti dhuratë",
  "scent": "Pishe · Kanellë",
  "ingredients": "Dyllë soje natyral, aroma bimore, fitil pambuku organik",
  "description": "2 qirinj artizanalë me aromë pishe dhe kanellë, të paketuar në një kuti festive elegante. Seti është krijuar për të sjellë atmosferën e ngrohtë të dimrit dhe është një zgjedhje ideale si dhuratë për festat e fundvitit."
},
{
  "id": "rosae-serata",
  "name": "Rosa Serata",
  "price": 1100,
  "category": "romantike",
  "tag": "Romantike · Trëndafil",
  "image": "images/romantike.avif",
  "badge": "Romantike",
  "hours": "40 orë",
  "wax": "Dyllë soje natyral",
  "size": "250 g",
  "scent": "Trëndafil · Musk",
  "ingredients": "Dyllë soje natyral, vajra aromatikë premium, fitil pambuku organik",
  "description": "Qiri artizanal me aromë trëndafili dhe musk, i krijuar për të sjellë një atmosferë romantike dhe relaksuese. Paketohet me letër mëndafshi dhe lule dekorative, duke e bërë një dhuratë elegante për çdo rast të veçantë."
},
{
  "id": "velveti-rose",
  "name": "Velvet Rose",
  "price": 1800,
  "category": "romantike",
  "tag": "Romantike · Premium",
  "image": "images/trendafil.avif",
  "badge": "",
  "hours": "50 orë",
  "wax": "Dyllë soje",
  "size": "300 g",
  "scent": "Trëndafil i kuq · Velvet Musk",
  "ingredients": "Dyllë soje natyral, aroma premium, fitil pambuku",
  "description": "Qiri premium me trëndafil të kuq dhe velvet musk. Dhurata elegante për ata me shije të rafinuar."
},
{
  "id": "glowy-globes",
  "name": "Glowy Globes",
  "price": 4000,
  "category": "festive",
  "tag": "Festive · Sandalwood",
  "image": "images/globes.jpg",
  "badge": "Premium",
  "hours": "70 orë",
  "wax": "Dyllë soje",
  "size": "Set 3 sfera",
  "scent": "Sandalwood",
  "ingredients": "Dyllë soje natyral, aroma sandalwood, fitil pambuku",
  "description": "Sfera qirinjsh premium me aromë sandalwood dhe dizajn elegant. Dhurata perfekte për çdo rast të veçantë."
},
{
  "id": "mini-tealight-set",
  "name": "Mini Tealight Set",
  "price": 1400,
  "category": "dekorative",
  "tag": "Dhuratë · Mini Set",
  "image": "images/set dasme.webp",
  "badge": "Natyral",
  "hours": "15 orë (secili)",
  "wax": "Dyllë soje",
  "size": "Set 6 copë",
  "scent": "Vanilje · Lavandë · Portokall",
  "ingredients": "Dyllë soje natyral, aroma mikse, fitil pambuku mini",
  "description": "Set qirinjsh mini natyralë, të bukur dhe aromatikë. Ideal si favor për dasma, evente ose si dhuratë e vogël."
},
{
  "id": "sete-ditelindjesh",
  "name": "Set Ditëlindjesh",
  "price": 3200,
  "category": "festive",
  "tag": "Festive · Dhuratë",
  "image": "images/set personalizuar.webp",
  "badge": "Ditëlindje",
  "hours": "50 orë",
  "wax": "Dyllë soje",
  "size": "Set dhuratë",
  "scent": "Vanilje · Trëndafil",
  "ingredients": "Qiri me dyllë soje, kartë personale, kuti dhuratë elegante",
  "description": "Qiri artizanal i shoqëruar me një kuti dhuratë elegante dhe kartë personale. Dhurata ideale për të festuar ditëlindjet dhe momentet e veçanta."
}
];